### ISSUE TITLE
amazon music 

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#8]
@pascalopitz you can add it but wont open

![screenshot from 2016-12-16 21-28-42](https://cloud.githubusercontent.com/assets/15007183/21283851/2fe38d70-c3d9-11e6-9d53-54104a178a8c.png)

**Comment by pascalopitz** [comment]
See https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/6#issuecomment-265943975

**Comment by pascalopitz** [comment]
Can you check this one again?

**Comment by xxcriticxx** [comment]
i will test this when i get home for you

**Comment by xxcriticxx** [comment]
![screenshot from 2017-06-08 20-52-49](https://user-images.githubusercontent.com/15007183/26956565-b717d2ba-4c8c-11e7-848d-f1c565fc1770.png)

**Comment by pascalopitz** [comment]
I changed the useragent again, and it's seemingly brought Google Play to live. Is amazon music affected?

**Comment by xxcriticxx** [comment]
i will test and let you knwo

**Comment by xxcriticxx** [comment]
i tested 0.0.15

![screenshot from 2017-08-08 20-12-05](https://user-images.githubusercontent.com/15007183/29099927-2d3cf4ca-7c76-11e7-8cf8-6901e78e4897.png)

i get this far i cant click next. i can add the service by clicking on the link and signing in through the browser

![screenshot from 2017-08-08 20-10-32](https://user-images.githubusercontent.com/15007183/29099967-81801134-7c76-11e7-8d4c-3b774cae91e3.png)

service shows up but cant do much with it because search dont work 


[error log.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/1209930/error.log.txt)

**Comment by pascalopitz** [comment]
Can you check  v0.1.0-alpha2? That will at least get rid of the next button problem, and show you the library home withthe new service. Not sure about the search?

**Comment by xxcriticxx** [comment]
log looks like shitty i will upload next time to pastebin

**Comment by xxcriticxx** [comment]
question is it better to uninstall old ver or install new one on top? or it makes no difference

**Comment by pascalopitz** [comment]
I don't think it makes a difference. Maybe remove and re-add the service though.
I have found out how the search can be fixed as well. They provide a presentationMap XML, that contains a section with search mappings, i.e.

`<SearchCategories>
<Category id="artists" mappedId="search:people"/>
<Category id="tracks" mappedId="search:sounds"/>
</SearchCategories>`

This tells us what and how to search.
Will work on that the next few days.

**Comment by pascalopitz** [comment]
That might mean a few UI changes. Not sure what's best. How about a dropdown to change between the possible modes, instead of the three tabs:

![image](https://user-images.githubusercontent.com/271740/29146316-b5022c8e-7d9f-11e7-8a2c-ff8e56c5ffa2.png)

**Comment by xxcriticxx** [comment]
Doesn't matter for me as long it works three tabs is quick and simple

**Comment by pascalopitz** [comment]
The problem is that services might map less or more, depending on what searches they offer. It makes sense to provide the very list they map, but it might get crammed if there were more than three.

**Comment by xxcriticxx** [comment]
now the next icon is missing

**Comment by pascalopitz** [comment]
The tab will hide automatically when you authed in the browser. There is no
next action.

**Comment by xxcriticxx** [comment]
ok so i did through the browser service was added put search dont work

**Comment by pascalopitz** [comment]
Exactly ... that's where the search mappings will come in.

**Comment by xxcriticxx** [comment]
do you need any logs?

**Comment by pascalopitz** [comment]
No, I think I am ok from here.

**Comment by xxcriticxx** [comment]
give me few i will upload them to paste bin there is few errors

**Comment by xxcriticxx** [comment]
https://pastebin.com/GD4PaF9T

**Comment by xxcriticxx** [comment]
if i load music from amazon through my phone i can control it on the laptop with no problems

![screenshot from 2017-08-09 20-12-07](https://user-images.githubusercontent.com/15007183/29149023-4b1ba300-7d3f-11e7-8368-4e8e610af34e.png)

**Comment by pascalopitz** [comment]
Try this: https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.1.0-alpha3

Make sure to remove and re-add the service though.

**Comment by xxcriticxx** [comment]
new search shows up but still dont work needs arrow to run through it 

https://pastebin.com/kmMTtmZR

![screenshot from 2017-08-10 06-11-54](https://user-images.githubusercontent.com/15007183/29166120-28e75398-7d93-11e7-8c48-fbd633e74088.png)

**Comment by pascalopitz** [comment]
So that's searching the local library only. If you click on the service icon, the search scope on top will change also. Then perform a search, and let me know if amazon works or not?

**Comment by xxcriticxx** [comment]
when i click on music service icon this happens and if i type something on top nothing happens

![screenshot from 2017-08-10 06-44-47](https://user-images.githubusercontent.com/15007183/29167243-a50593b4-7d97-11e7-8a13-d5b3710985ac.png)

**Comment by pascalopitz** [comment]
can you open the console and type: `JSON.stringify(window.localStorage, true, 4)`

**Comment by xxcriticxx** [comment]
![screenshot from 2017-08-10 06-57-37](https://user-images.githubusercontent.com/15007183/29167643-41b8a056-7d99-11e7-99e9-fa509e33542a.png)

**Comment by pascalopitz** [comment]
Can you re-download the alpha release and try again?

**Comment by xxcriticxx** [comment]
alpha3?

**Comment by pascalopitz** [comment]
Yes, I forced pushed an update & new build

**Comment by xxcriticxx** [comment]
same but now when i click on music service artist album track show menu shows up

https://pastebin.com/PgwGCN1V

**Comment by pascalopitz** [comment]
Now I'm out of my wits ...No idea

**Comment by pascalopitz** [comment]
"User has not updated Sonos system" is something I get occasionally on the Sonos service as well, but then it goes away the second time around. Same story on Amazon?

**Comment by xxcriticxx** [comment]
i see connecting to sonos system when my laptop comes out from sleep from time to time 

my sonos is up to date as far as i know

same results search still dont work only thing thats new is artist track menu shows up on top now

**Comment by xxcriticxx** [comment]
any new test builds?

**Comment by pascalopitz** [comment]
Not at this stage. I cannot test against amazon music, because it's not available in Australia, and at this stage I don't know why the search doesn't work or if it just doesn't bring back results?

The wake-up issue I am looking into, but haven't found a solution for yet.

As for the "User has not updated Sonos system" fault, again, I don't know why the SMAPI services return that, but it has nothing to do with the Players themselves, but with the HTTP headers or payload I send up. It's undocumented as to what exactly, so I have no idea as to why. The fault goes away on Spotify after you try and browse the service again. Is this the same for Amazon music?

**Comment by xxcriticxx** [comment]
Do you want to test different service?

**Comment by pascalopitz** [comment]
Well, for me it works for Spotify and soundcloud. Google Music is broken
for some reason, but that happened because they somehow changed their api.
Feedback on all other services would be welcome.

**Comment by MaxJonasG** [comment]
just to confirm that while deezer now works for me Amazon doesn't. As described the search box does not change to Amazon, it stays at the local library (for deezer the icon in front of it changes)

**Comment by pascalopitz** [comment]
Is there any stack traces in the  console, @MaxJonasG ?

**Comment by MaxJonasG** [comment]
this is all that comes up
![screenshot from 2017-08-14 18-59-58](https://user-images.githubusercontent.com/25565941/29284651-831a3cb6-8123-11e7-9319-2ba5220af186.png)

**Comment by pascalopitz** [comment]
And that keeps happening the second time you browse? With spotify I get
this error the first time I browse, but then the session works normally
after that. I have no idea which header I need to send to make this go away.

**Comment by MaxJonasG** [comment]
yes, that keeps on happening (to be fair I'm not too fussed about Amazon Music services as I don't really use it - I just got a free Apple Music subscription so in theory could test that as well but I'll be away on vacation for the next 3 weeks.)

**Comment by pascalopitz** [comment]
I did a slight change to the user agent string. Let me know if still the
case in alpha5

**Comment by MaxJonasG** [comment]
yes, search now works (with the same hickup as for deezer)

**Comment by pascalopitz** [comment]
Ok, I pushed alpha6, which should address the search bar hiccup and the playing of lists and albums for Deezer as well as Amazon. If things play and search works for Amazon, can I close this ticket?

**Comment by xxcriticxx** [comment]
@pascalopitz alpha6 still shows up as alpha5

```
Unpacking sonos-controller-unofficial (0.1.0-alpha5-195) ...
Setting up sonos-controller-unofficial (0.1.0-alpha5-195) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
```

**Comment by xxcriticxx** [comment]
in alpha5 i can add service and i can browse service. covers dont download small problem. i can add remove tracks/albums. all tracks do play and work. wakeup from sleep also works finds sonso system right away. in full screen mode app blinks very often. search for me still dont work it looks like when i type someone is removing what i type many console errors.

**Comment by pascalopitz** [comment]
Ok, too many issues at once here. What I get is that unlike before Amazon can authenticate and play music. I'll close this issue. Any improvements to amazon music please open different issues.
I promoted the alpha to v0.1.0. I think it's as good if not better than the pre-redux build.
